import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

class RoadSafeIcons {
  RoadSafeIcons._();

  // Navigation
  static const IconData home = PhosphorIcons.regular.house;
  static const IconData homeFilled = PhosphorIcons.fill.house;
  static const IconData map = PhosphorIcons.regular.map;
  static const IconData mapFilled = PhosphorIcons.fill.map;
  static const IconData report = PhosphorIcons.regular.plusCircle;
  static const IconData reportFilled = PhosphorIcons.fill.plusCircle;
  static const IconData alerts = PhosphorIcons.regular.bell;
  static const IconData alertsFilled = PhosphorIcons.fill.bell;
  static const IconData profile = PhosphorIcons.regular.user;
  static const IconData profileFilled = PhosphorIcons.fill.user;
  static const IconData menu = PhosphorIcons.regular.list;
  static const IconData back = PhosphorIcons.regular.arrowLeft;
  static const IconData forward = PhosphorIcons.regular.arrowRight;
  static const IconData close = PhosphorIcons.regular.x;
  static const IconData more = PhosphorIcons.regular.threeDots;
  static const IconData settings = PhosphorIcons.regular.gear;
  static const IconData search = PhosphorIcons.regular.magnifyingGlass;
  static const IconData filter = PhosphorIcons.regular.funnel;
  static const IconData layers = PhosphorIcons.regular.layersThree;
  static const IconData location = PhosphorIcons.regular.mapPin;
  static const IconData navigation = PhosphorIcons.regular.navigationArrow;
  static const IconData share = PhosphorIcons.regular.share;
  static const IconData bookmark = PhosphorIcons.regular.bookmark;
  static const IconData info = PhosphorIcons.regular.info;
  static const IconData edit = PhosphorIcons.regular.pencil;
  static const IconData refresh = PhosphorIcons.regular.arrowsClockwise;
  static const IconData camera = PhosphorIcons.regular.camera;
  static const IconData flash = PhosphorIcons.regular.flashAuto;
  static const IconData gallery = PhosphorIcons.regular.image;
  static const IconData calendar = PhosphorIcons.regular.calendar;
  static const IconData clock = PhosphorIcons.regular.clock;
  static const IconData caretRight = PhosphorIcons.regular.caretRight;
  static const IconData caretDown = PhosphorIcons.regular.caretDown;
  static const IconData check = PhosphorIcons.regular.check;
  static const IconData checkCircle = PhosphorIcons.regular.checkCircle;
  static const IconData xCircle = PhosphorIcons.regular.xCircle;
  static const IconData warning = PhosphorIcons.regular.warning;
  static const IconData warningCircle = PhosphorIcons.regular.warningCircle;
  static const IconData warningOctagon = PhosphorIcons.regular.warningOctagon;
  static const IconData question = PhosphorIcons.regular.question;
  static const IconData help = PhosphorIcons.regular.question;
  static const IconData lock = PhosphorIcons.regular.lockSimple;
  static const IconData spinner = PhosphorIcons.regular.spinner;
  static const IconData circle = PhosphorIcons.regular.circle;
  static const IconData flag = PhosphorIcons.regular.flag;
  static const IconData shield = PhosphorIcons.regular.shield;
  static const IconData shieldCheck = PhosphorIcons.regular.shieldCheck;
  static const IconData star = PhosphorIcons.regular.star;
  static const IconData gift = PhosphorIcons.regular.gift;
  static const IconData paperPlane = PhosphorIcons.regular.paperPlane;
  static const IconData eyeClosed = PhosphorIcons.regular.eyeClosed;
  static const IconData idCard = PhosphorIcons.regular.idCard;
  static const IconData signOut = PhosphorIcons.regular.signOut;
  static const IconData signIn = PhosphorIcons.regular.signIn;
  static const IconData logout = PhosphorIcons.regular.signOut;
  static const IconData user = PhosphorIcons.regular.user;
  static const IconData users = PhosphorIcons.regular.users;
  static const IconData heart = PhosphorIcons.regular.heart;
  static const IconData bell = PhosphorIcons.regular.bell;
  static const IconData bellFilled = PhosphorIcons.fill.bell;
  static const IconData plus = PhosphorIcons.regular.plus;
  static const IconData minus = PhosphorIcons.regular.minus;
  static const IconData download = PhosphorIcons.regular.download;
  static const IconData upload = PhosphorIcons.regular.upload;

  // Hazard-specific icons
  static const IconData pothole = PhosphorIcons.regular.pothole;
  static const IconData carCrash = PhosphorIcons.regular.carCrash;
  static const IconData cloudFog = PhosphorIcons.regular.cloudFog;
  static const IconData speedBump = PhosphorIcons.regular.speedBump;
  static const IconData waves = PhosphorIcons.regular.waves;
  static const IconData roadHorizon = PhosphorIcons.regular.roadHorizon;
  static const IconData hammer = PhosphorIcons.regular.hammer;
  static const IconData construction = PhosphorIcons.regular.hammer;
  static const IconData cloud = PhosphorIcons.regular.cloud;
  static const IconData sun = PhosphorIcons.regular.sun;
  static const IconData fire = PhosphorIcons.regular.fire;
  static const IconData satellite = PhosphorIcons.regular.satellite;
  static const IconData cpu = PhosphorIcons.regular.cpu;
  static const IconData note = PhosphorIcons.regular.note;
  static const IconData folderOpen = PhosphorIcons.regular.folderOpen;
  static const IconData image = PhosphorIcons.regular.image;
  static const IconData gps = PhosphorIcons.regular.gps;
  static const IconData car = PhosphorIcons.regular.car;
  static const IconData mapPin = PhosphorIcons.regular.mapPin;
  static const IconData retake = PhosphorIcons.regular.arrowCounterClockwise;
  static const IconData retakePhoto = PhosphorIcons.regular.arrowCounterClockwise;
}